import Button from '@/components/ui/Button';
import Icon from '@/components/ui/Icon';
import { revealProps } from '@/lib/reveal';

type ServicePage = { title: string; category: string; summary: string; image: string; deliverables: string[]; index: number };

export default function ServiceExperience({ page }: { page: ServicePage }) {
  const outcomes = ['Clear direction', 'Visible delivery', 'A stronger foundation'];
  const reasons = ['Built around your real workflow', 'Senior practitioners, not handoffs', 'Clear decisions at every stage', 'Progress you can see and measure'];
  const visual = page.image.startsWith('/mockups/') ? '/service-visuals/team-collaboration.png' : page.image;
  return <main className="bg-white text-ink">
    <section className="relative isolate min-h-[100svh] overflow-hidden bg-navy pt-[var(--header-h)] text-white">
      <img src={visual} alt={`${page.title} team and technology`} loading="lazy" decoding="async" className="absolute inset-0 h-full w-full object-cover opacity-35" />
      <div aria-hidden className="absolute inset-0 bg-navy/70" />
      <div aria-hidden className="absolute inset-x-0 bottom-0 h-1/2 bg-[linear-gradient(0deg,#020617,transparent)]" />
      <div className="container-site relative flex min-h-[calc(100svh-var(--header-h))] items-center py-16"><div className="max-w-2xl" {...revealProps()}>
        <p className="text-micro font-bold uppercase tracking-label text-amber">{page.category} · Eaquirs Tech</p><h1 className="mt-5 text-h1 font-bold leading-[1.02] text-white">{page.title}</h1><p className="mt-7 max-w-xl text-body-lg leading-relaxed text-white/70">{page.summary}</p><div className="mt-9 flex flex-wrap gap-4"><Button href="/contact" size="md" arrow className="bg-amber text-white hover:bg-amber-bright">Discuss your project</Button><span className="inline-flex min-h-11 items-center rounded-full border border-white/15 px-4 py-2 text-body-sm text-white/70">Built for real operations</span></div>
      </div></div>
    </section>

    <section className="flex min-h-[100svh] items-center bg-white py-16"><div className="container-site w-full"><div className="mx-auto max-w-3xl text-center" {...revealProps()}><p className="text-micro font-bold uppercase tracking-label text-amber">What you gain</p><h2 className="mt-4 text-h2 font-bold text-ink">Clear work. Useful results.</h2><p className="mt-5 text-body leading-relaxed text-body">We shape the work around the decisions, people, and results that matter to your team.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{outcomes.map((outcome, index) => <article {...revealProps(index)} key={outcome} className={`border border-amber-deep/25 bg-amber p-7 shadow-card ${['rounded-tl-[3rem]','rounded-2xl','rounded-br-[3rem]'][index]}`}><span className="text-micro font-bold text-navy/65">0{index + 1}</span><h3 className="mt-10 text-xl font-semibold text-navy">{outcome}</h3><p className="mt-4 text-body-sm leading-relaxed text-navy/75">Experienced delivery focused on the outcome you need, not a bundle of hours.</p></article>)}</div></div></section>

    <section className="flex min-h-[100svh] items-center bg-navy py-16 text-white"><div className="container-site grid w-full items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div {...revealProps()}><p className="text-micro font-bold uppercase tracking-label text-amber">What we deliver</p><h2 className="mt-4 text-h2 font-bold text-white">The work your team needs, done properly.</h2><p className="mt-5 max-w-md text-body leading-relaxed text-white/65">A focused engagement with clear ownership and practical next steps.</p><Button href="/contact" size="md" arrow className="mt-8 bg-amber text-white hover:bg-amber-bright">Scope the work</Button></div><div className="grid gap-3 sm:grid-cols-2">{page.deliverables.map((item, index) => <article {...revealProps(index)} key={item} className={`border border-white/10 bg-white/[.03] p-6 transition-colors hover:border-amber/60 hover:bg-white/[.06] ${index === 0 ? 'sm:col-span-2' : ''}`}><div className="flex items-center justify-between"><span className="text-micro font-bold text-amber">0{index + 1}</span><Icon name="arrow" className="h-4 w-4 text-cyan-300" /></div><h3 className="mt-10 text-lg font-semibold text-white">{item}</h3><p className="mt-3 text-body-sm leading-relaxed text-white/60">Clear ownership, tested work, and a handover your team can use.</p></article>)}</div></div></section>

    <section className="flex min-h-[100svh] items-center bg-white py-16"><div className="container-site w-full"><div {...revealProps()}><p className="text-micro font-bold uppercase tracking-label text-amber">Why this approach</p><h2 className="mt-4 max-w-2xl text-h2 font-bold text-ink">Built with the discipline production work requires.</h2></div><div className="mt-10 grid gap-3 md:grid-cols-2">{reasons.map((reason, index) => <div {...revealProps(index)} key={reason} className="flex items-center gap-4 border border-amber-deep/25 bg-amber px-5 py-5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-navy text-sm font-bold text-white">0{index + 1}</span><p className="font-medium text-navy">{reason}</p></div>)}</div><div className="mt-10 overflow-hidden border border-line bg-white" {...revealProps(2)}><img src={visual} alt="Eaquirs Tech delivery team" className="mx-auto max-h-[20rem] w-full object-cover" /></div></div></section>

    <section className="flex min-h-[100svh] items-center bg-white py-16"><div className="container-site w-full"><div className="mx-auto max-w-4xl text-center" {...revealProps()}><p className="text-micro font-bold uppercase tracking-label text-amber">Is this right for you?</p><h2 className="mt-4 text-h2 font-bold text-ink">A strong fit when the outcome matters.</h2></div><div className="mx-auto mt-10 grid max-w-5xl gap-5 md:grid-cols-2"><article {...revealProps()} className="border border-amber-deep/25 bg-amber p-8 transition-all duration-base hover:-translate-y-2 hover:shadow-card-hover"><h3 className="text-xl font-semibold text-navy">A good fit</h3><ul className="mt-6 space-y-4">{['You need software that supports a real business process.','You value clear communication and experienced ownership.','You want a capable team that can deliver and evolve the work.'].map(x => <li key={x} className="flex gap-3 text-body-sm leading-relaxed text-navy/80"><Icon name="check" className="mt-0.5 h-4 w-4 shrink-0 text-navy" />{x}</li>)}</ul></article><article {...revealProps(1)} className="border border-line bg-[#f7f9fc] p-8 transition-all duration-base hover:-translate-y-2 hover:border-amber/50 hover:shadow-card-hover"><h3 className="text-xl font-semibold text-ink">Not the right fit</h3><ul className="mt-6 space-y-4">{['You need the cheapest possible option.','The work has no owner or agreed outcome.','You are looking only for a quick, unmaintained prototype.'].map(x => <li key={x} className="flex gap-3 text-body-sm leading-relaxed text-body"><span className="text-amber-deep">×</span>{x}</li>)}</ul></article></div><div className="mt-12 text-center" {...revealProps(2)}><Button href="/contact" size="md" arrow className="bg-amber px-7 text-white hover:bg-amber-bright">Start a conversation</Button></div></div></section>
  </main>;
}
