import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import Button from '@/components/ui/Button';
import ServiceExperience from '@/components/sections/ServiceExperience';

type Service = { title: string; category: string; summary: string; image: string; deliverables: string[] };
const raw: Array<[string, Service]> = [
  ['product-engineering/full-stack-web-development', { title: 'Full-stack web development', category: 'Product engineering', summary: 'Production-ready web products built across interface, backend, data, and deployment by one accountable team.', image: '/uploads/services/363f40e1-4d1d-4c30-89d7-5712102dbf83.png', deliverables: ['Product architecture', 'Frontend engineering', 'Backend & data services', 'Release-ready deployment'] }],
  ['product-engineering/mobile-app-development', { title: 'Mobile app development', category: 'Product engineering', summary: 'Reliable mobile experiences designed for real users, app-store delivery, and a roadmap that can grow.', image: '/uploads/services/014cc575-2241-4c04-a21f-4fdc7032f7eb.png', deliverables: ['iOS & Android delivery', 'Cross-platform builds', 'Secure app integration', 'Ongoing release support'] }],
  ['product-engineering/api-backend-architecture', { title: 'API & backend architecture', category: 'Product engineering', summary: 'Secure, scalable services and domain models that keep important business logic dependable as demand grows.', image: '/service-visuals/api-team.png', deliverables: ['API design', 'Data modelling', 'Authentication & roles', 'Performance foundations'] }],
  ['product-engineering/devops-cicd', { title: 'DevOps & CI/CD', category: 'Product engineering', summary: 'Automated delivery practices that make releases safer, faster, observable, and repeatable.', image: '/uploads/services/c5ffdd08-1f64-40af-93b8-464042a68f46.png', deliverables: ['Automated pipelines', 'Cloud infrastructure', 'Monitoring & alerts', 'Release governance'] }],
  ['product-engineering/mvp-development', { title: 'MVP development', category: 'Product engineering', summary: 'A focused first product that validates the right idea while establishing a solid technical foundation.', image: '/uploads/services/fe95ca16-cdf5-42f2-8507-6d0f362d1476.png', deliverables: ['MVP scope', 'Rapid build cycles', 'Launch planning', 'Growth-ready architecture'] }],
  ['business-systems/real-estate-erp', { title: 'Real estate ERP', category: 'Business systems', summary: 'One dependable system for properties, customers, agents, payments, approvals, and project reporting.', image: '/uploads/services/d88f0089-b664-4409-8376-c2a0da6ae4e1.png', deliverables: ['Project & plot management', 'Customer payment records', 'Agent workflows', 'Executive reporting'] }],
  ['business-systems/healthcare-management', { title: 'Healthcare management', category: 'Business systems', summary: 'Operational software that connects patient records, billing, pharmacy, laboratory, and clinical workflows.', image: '/uploads/services/8dd7ea20-fa2f-41f4-acae-0d217f0a0ca5.png', deliverables: ['Patient administration', 'Billing workflows', 'Clinical operations', 'Role-based access'] }],
  ['business-systems/inventory-manufacturing', { title: 'Inventory & manufacturing', category: 'Business systems', summary: 'Clear operational control for stock, suppliers, production stages, traceability, and reporting.', image: '/uploads/services/cc47d428-5705-4cef-87a4-e549dae35401.png', deliverables: ['Stock control', 'Production workflows', 'Supplier management', 'Operational reporting'] }],
  ['business-systems/custom-erp-build', { title: 'Custom ERP build', category: 'Business systems', summary: 'A business platform shaped around your own roles, approvals, reports, and operating model.', image: '/uploads/services/8e0238d4-89fc-4b95-bb83-97bff213ea0e.png', deliverables: ['Workflow discovery', 'Custom modules', 'Approval systems', 'Live business dashboards'] }],
  ['business-systems/multi-tenant-platforms', { title: 'Multi-tenant platforms', category: 'Business systems', summary: 'Subscription-ready SaaS architecture with secure tenant separation, permissions, and operational tooling.', image: '/service-visuals/saas-team.png', deliverables: ['Tenant architecture', 'Subscriptions & billing', 'Access controls', 'Platform operations'] }],
  ['ai-automation/llm-integration', { title: 'LLM integration', category: 'AI & automation', summary: 'Language-model features connected to your product with reliable context, guardrails, and evaluation.', image: '/service-visuals/llm-team.png', deliverables: ['RAG & knowledge retrieval', 'Prompt engineering', 'Safety guardrails', 'Evaluation & monitoring'] }],
  ['ai-automation/ai-powered-chatbots', { title: 'AI-powered chatbots', category: 'AI & automation', summary: 'Knowledge-aware assistants that improve customer support and internal operations without losing control.', image: '/service-visuals/chatbot-team.png', deliverables: ['Support assistants', 'Document Q&A', 'Human hand-off', 'Conversation analytics'] }],
  ['ai-automation/workflow-automation', { title: 'Workflow automation', category: 'AI & automation', summary: 'Automation that routes, summarises, scores, and completes repetitive operational work with traceability.', image: '/uploads/services/cfcee384-5b68-4ffb-a5f1-2d179f65d093.png', deliverables: ['Process mapping', 'Automated routing', 'Approvals & alerts', 'Operational audit trail'] }],
  ['ai-automation/data-extraction-analytics', { title: 'Data extraction & analytics', category: 'AI & automation', summary: 'Turn documents, images, and scattered business data into structured information and practical insight.', image: '/uploads/services/97e20872-bb69-440a-9163-f4d47b8affe9.png', deliverables: ['Document extraction', 'Data normalisation', 'Insight dashboards', 'Decision-ready reports'] }],
  ['ai-automation/custom-ai-model-integration', { title: 'Custom AI model integration', category: 'AI & automation', summary: 'Domain-specific AI capabilities engineered, evaluated, and deployed for the outcomes your team needs.', image: '/service-visuals/model-team.png', deliverables: ['Use-case evaluation', 'Model integration', 'Quality testing', 'Production operations'] }],
  ['rescue-modernization/codebase-rescue', { title: 'Codebase rescue', category: 'Rescue & modernization', summary: 'A clear technical recovery plan for software that has become hard to change, trust, or release safely.', image: '/service-visuals/rescue-team.png', deliverables: ['Codebase assessment', 'Risk prioritisation', 'Stability improvements', 'Recovery roadmap'] }],
  ['rescue-modernization/vendor-replacement', { title: 'Vendor replacement', category: 'Rescue & modernization', summary: 'A controlled handover from an unreliable vendor that protects continuity while rebuilding confidence.', image: '/service-visuals/vendor-team.png', deliverables: ['Technical handover', 'Continuity planning', 'Knowledge recovery', 'Delivery transition'] }],
  ['rescue-modernization/legacy-system-rewrite', { title: 'Legacy system rewrite', category: 'Rescue & modernization', summary: 'A staged modernisation path that replaces fragile technology without interrupting day-to-day operations.', image: '/service-visuals/legacy-team.png', deliverables: ['Legacy assessment', 'Phased migration', 'Data transition', 'Modern platform delivery'] }],
  ['rescue-modernization/performance-remediation', { title: 'Performance remediation', category: 'Rescue & modernization', summary: 'Measured fixes for slow queries, unstable infrastructure, bottlenecks, and avoidable operational cost.', image: '/service-visuals/performance-team.png', deliverables: ['Performance analysis', 'Database optimisation', 'Infrastructure tuning', 'Ongoing observability'] }],
  ['specialist-services/payments-integrations', { title: 'Payments & integrations', category: 'Specialist services', summary: 'Secure payments, subscriptions, webhooks, and third-party systems implemented end to end.', image: '/service-visuals/payments-team.png', deliverables: ['Payment gateways', 'Subscription billing', 'Third-party APIs', 'Secure webhooks'] }],
  ['specialist-services/product-design-ux', { title: 'Product design & UX', category: 'Specialist services', summary: 'Clear, thoughtful interfaces and design systems that help people complete valuable work with confidence.', image: '/service-visuals/design-team.png', deliverables: ['User journeys', 'Product interfaces', 'Design systems', 'Usability refinement'] }],
  ['specialist-services/quality-assurance', { title: 'Quality assurance', category: 'Specialist services', summary: 'Practical manual and automated testing that protects software quality before it reaches users.', image: '/service-visuals/qa-team.png', deliverables: ['Test strategy', 'Manual QA', 'Automation coverage', 'Release validation'] }],
  ['specialist-services/staff-augmentation', { title: 'Staff augmentation', category: 'Specialist services', summary: 'Senior Eaquirs engineers embedded with your team for focused capacity and accountable delivery.', image: '/service-visuals/staff-team.png', deliverables: ['Senior engineering talent', 'Fast onboarding', 'Team collaboration', 'Flexible engagement'] }],
];
const services = Object.fromEntries(raw.map(([key, page], index) => [key, { ...page, index }]));
export function generateStaticParams() { return raw.map(([key]) => { const [category, service] = key.split('/'); return { category, service }; }); }
export async function generateMetadata({ params }: { params: Promise<{ category: string; service: string }> }): Promise<Metadata> { const { category, service } = await params; const page = services[`${category}/${service}`]; return page ? { title: `${page.title} | Eaquirs Tech`, description: page.summary } : {}; }

export default async function ServicePage({ params }: { params: Promise<{ category: string; service: string }> }) {
 const { category, service } = await params; const page = services[`${category}/${service}`]; if (!page) notFound();
 const light = page.index % 3 === 1; const flip = page.index % 2 === 1; const shapes = ['rounded-[3rem_0_3rem_0]','rounded-[0_4rem_0_4rem]','rounded-[5rem_1.25rem_5rem_1.25rem]']; const shape = shapes[page.index % 3];
 return <ServiceExperience page={page} />;
 /* return <main>
  <section className={`relative isolate flex min-h-[100svh] items-center overflow-hidden pt-[var(--header-h)] ${light ? 'bg-[#f4f8fb] text-ink' : 'bg-navy text-white'}`}><div aria-hidden className={`absolute -right-32 -top-24 h-[32rem] w-[32rem] rounded-full blur-3xl ${light ? 'bg-sky-200/70' : 'bg-amber/15'}`} /><div className={`container-site relative grid w-full items-center gap-10 py-12 lg:grid-cols-2 lg:gap-16 ${flip ? 'lg:[&>*:first-child]:order-2' : ''}`}><div className="max-w-xl"><p className="text-micro font-bold uppercase tracking-label text-amber">{page.category} · {String(page.index + 1).padStart(2,'0')}</p><h1 className={`mt-5 text-h1 font-bold leading-[1.02] ${light ? 'text-ink' : 'text-white'}`}>{page.title}</h1><p className={`mt-7 text-body-lg leading-relaxed ${light ? 'text-body' : 'text-on-dark-muted'}`}>{page.summary}</p><div className="mt-8"><Button href="/contact" size="lg" arrow className="bg-amber text-white hover:bg-amber-bright">Plan your project</Button></div></div><div className={`relative overflow-hidden border p-3 shadow-mega ${shape} ${light ? 'border-navy/10 bg-white' : 'border-white/15 bg-white/5'}`}><img src={page.image} alt={`${page.title} visual`} className="aspect-[4/3] w-full object-cover" /><div aria-hidden className="absolute inset-3 border border-amber/30" /></div></div></section>
  <section className="flex min-h-[100svh] items-center bg-white py-16"><div className={`container-site grid w-full items-center gap-10 lg:grid-cols-[.75fr_1.25fr] ${flip ? 'lg:[&>*:first-child]:order-2' : ''}`}><div><p className="text-micro font-bold uppercase tracking-label text-amber">The capability</p><h2 className="mt-4 text-h2 font-bold leading-tight text-ink">Important work, made clear.</h2><p className="mt-5 text-body leading-relaxed text-body">Every engagement is shaped around visible decisions, measurable progress, and a useful handover.</p></div><div className={`grid gap-4 sm:grid-cols-2 ${page.index % 3 === 2 ? 'sm:[&>*:first-child]:col-span-2' : ''}`}>{page.deliverables.map((item, i) => <article key={item} className={`min-h-48 border border-line bg-[#fbfcfd] p-6 transition-all hover:-translate-y-1 hover:border-amber/50 hover:shadow-card ${shapes[(page.index+i)%3]}`}><span className="text-micro font-bold text-amber">0{i+1}</span><h3 className="mt-9 text-[1.2rem] font-semibold text-ink">{item}</h3><p className="mt-3 text-body-sm leading-relaxed text-body">Defined scope, experienced ownership, and a result your team can build on.</p></article>)}</div></div></section>
  <section className={`flex min-h-[100svh] items-center py-16 ${light ? 'bg-navy text-white' : 'bg-[#f2f7f8] text-ink'}`}><div className="container-site w-full"><div className="mx-auto max-w-2xl text-center"><p className="text-micro font-bold uppercase tracking-label text-amber">A delivery rhythm</p><h2 className={`mt-4 text-h2 font-bold ${light ? 'text-white' : 'text-ink'}`}>Momentum without the mystery.</h2></div><div className="mx-auto mt-12 grid max-w-6xl gap-4 md:grid-cols-4">{['Discover','Design','Deliver','Evolve'].map((step,i) => <article key={step} className={`min-h-64 p-6 ${i === page.index % 4 ? 'bg-amber text-white' : light ? 'border border-white/15 bg-white/5 text-white' : 'border border-line bg-white text-ink'} ${shapes[i%3]}`}><span className={`text-micro font-bold ${i === page.index % 4 ? 'text-white/70' : 'text-amber'}`}>0{i+1}</span><h3 className="mt-12 text-xl font-semibold">{step}</h3><p className={`mt-4 text-body-sm leading-relaxed ${i === page.index % 4 ? 'text-white/80' : light ? 'text-white/65' : 'text-body'}`}>{['Clarify the outcome, constraints, and people who need to trust the work.','Turn the work into a focused plan with visible priorities.','Ship tested increments and keep every decision easy to follow.','Support adoption and identify the strongest next move.'][i]}</p></article>)}</div><div className="mt-12 text-center"><Button href="/contact" size="lg" arrow className="bg-amber px-8 text-white hover:bg-amber-bright">Talk to an expert</Button></div></div></section>
 </main>; */
}
