import { notFound } from 'next/navigation';
import Button from '@/components/ui/Button';
import BrandedVisual from '@/components/ui/BrandedVisual';
import { revealProps } from '@/lib/reveal';

type Page = { title: string; intro: string; image: string; focus: string[]; questions: string[]; receive: string[]; team: string[]; next: string[]; success: string[] };
const pages: Record<string, Page> = {
  'tech-strategy': { title: 'Tech strategy', intro: 'Get a practical technology plan that helps your team make sound decisions and gives stakeholders a clear view of what comes next.', image: '/service-visuals/consultancy-strategy.png', focus: ['Stack and platform selection', '12-month technical roadmap', 'Build, buy, and vendor decisions'], questions: ['Which technical decisions matter most this year?', 'Where is the current stack slowing the business?', 'What should the team build, defer, or retire?'], receive: ['Leadership strategy brief', 'Prioritised 12-month roadmap', 'Platform and vendor recommendations'], team: ['Working session with product and engineering leaders', 'Review of stack, roadmap, and delivery constraints', 'Decision workshop to align business and technical priorities'], next: ['Confirm the outcome', 'Review the current position', 'Present clear trade-offs', 'Support the first decision'], success: ['Leaders can explain the technical direction with confidence', 'Investment follows clear priorities instead of urgency', 'Engineering has a roadmap that supports the business plan'] },
  'ai-consulting': { title: 'AI consulting', intro: 'Identify where AI can genuinely help, then put the right controls in place before it reaches customers or operations teams.', image: '/service-visuals/consultancy-ai.png', focus: ['AI opportunity mapping', 'Model and provider evaluation', 'Governance and reliability plan'], questions: ['Which workflows are ready for AI support?', 'What accuracy and review are required?', 'Which approach fits the real operating cost?'], receive: ['Ranked AI opportunities', 'Model and provider recommendation', 'Safety and evaluation plan'], team: ['Sessions with workflow owners', 'Review of data, systems, and approvals', 'Prototype plan with human review'], next: ['Choose one high-value use case', 'Set success measures', 'Validate with real data', 'Plan a controlled rollout'], success: ['The use case has a measurable business purpose', 'Quality and review expectations are defined before launch', 'The team knows how to operate the feature safely'] },
  'product-consulting': { title: 'Product consulting', intro: 'Turn a promising idea into a focused product plan, with clear priorities, useful measures, and a realistic route to launch.', image: '/uploads/services/fe95ca16-cdf5-42f2-8507-6d0f362d1476.png', focus: ['MVP scope and sequencing', 'User-story mapping', 'Success metrics and roadmap'], questions: ['What must be in the first useful release?', 'Which user problem should be solved first?', 'What proves the product is ready to grow?'], receive: ['Focused MVP scope', 'Prioritised user-story map', 'Launch roadmap and success measures'], team: ['Workshops with founders and product owners', 'Review of users, constraints, and budget', 'Shared prioritisation before engineering'], next: ['Agree the release outcome', 'Validate the scope', 'Prepare the delivery backlog', 'Move into implementation'], success: ['The first release solves one important user problem well', 'The delivery team understands what is in and out of scope', 'Launch decisions are based on evidence, not assumptions'] },
  'digital-transformation': { title: 'Digital transformation', intro: 'Improve the systems behind your business in stages, with a plan built around the people who depend on them every day.', image: '/uploads/services/cc47d428-5705-4cef-87a4-e549dae35401.png', focus: ['Workflow discovery', 'Systems and data priorities', 'Phased implementation plan'], questions: ['Which manual process creates the most risk?', 'Where does data break down between teams?', 'What can improve operations without disruption?'], receive: ['Current workflow map', 'Systems and data priority list', 'Phased implementation plan'], team: ['Interviews with leaders and frontline users', 'Review of tools, data hand-offs, and reports', 'Planning around adoption and change'], next: ['Choose the first improvement', 'Set safe measures', 'Prepare the teams', 'Expand after proof'], success: ['The team spends less time managing avoidable manual work', 'Operational data becomes easier to trust and use', 'The business can improve systems without interrupting daily delivery'] },
  'architecture-review': { title: 'Architecture review', intro: 'See where your architecture is helping, where it is fragile, and what to address first before those issues become costly.', image: '/uploads/services/129b97b8-149c-45a5-abb7-a29ce3a262ab.png', focus: ['Codebase and infrastructure review', 'Risk and dependency assessment', 'Prioritised remediation plan'], questions: ['Which risks threaten reliability or delivery?', 'Where are the main dependencies and bottlenecks?', 'What needs attention first?'], receive: ['Architecture assessment', 'Risk and dependency register', 'Practical remediation roadmap'], team: ['Code and infrastructure review', 'Sessions with delivery and operations owners', 'Findings workshop with engineering leadership'], next: ['Share the current constraints', 'Review high-risk areas', 'Agree remediation milestones', 'Guide delivery with the plan'], success: ['The highest architectural risks are visible and owned', 'Engineering can sequence improvements without guesswork', 'The platform becomes easier to change and operate'] },
  'outsourcing-advisory': { title: 'IT outsourcing advisory', intro: 'Choose, manage, or replace a delivery partner with an independent technical view of scope, capability, and risk.', image: '/service-visuals/vendor-team.png', focus: ['Proposal and vendor evaluation', 'Technical due diligence', 'Handover and continuity plan'], questions: ['Does the partner understand the real scope?', 'What supports their delivery claims?', 'How will the business retain control?'], receive: ['Independent proposal review', 'Technical due-diligence summary', 'Handover and continuity checklist'], team: ['Sessions with sponsors and technical owners', 'Comparison of proposals and delivery plans', 'Decision meeting with selection criteria'], next: ['Set decision criteria', 'Review partner options', 'Define governance', 'Start with accountability'], success: ['The business selects a partner using evidence', 'The contract and governance model protect continuity', 'Leaders retain visibility into delivery quality and risk'] },
  'security-compliance': { title: 'Security & compliance review', intro: 'Understand your exposure, strengthen your controls, and prepare a practical route toward customer and compliance readiness.', image: '/uploads/services/129b97b8-149c-45a5-abb7-a29ce3a262ab.png', focus: ['Application and access review', 'Data protection assessment', 'Actionable control roadmap'], questions: ['Where could important data be exposed?', 'Which controls need attention first?', 'What evidence will customers expect?'], receive: ['Application and access assessment', 'Data protection gap summary', 'Prioritised control roadmap'], team: ['Secure sessions with engineering and operations', 'Assessment of data, access, dependencies, and infrastructure', 'Findings walkthrough with assigned actions'], next: ['Confirm scope', 'Address critical findings', 'Plan the control work', 'Reassess before key milestones'], success: ['Critical weaknesses are identified before they become incidents', 'Control improvements have clear owners and priorities', 'The business can show customers meaningful security progress'] },
  'fractional-cto': { title: 'Fractional CTO', intro: 'Bring experienced technical leadership into the decisions that matter, without adding a full-time executive role.', image: '/service-visuals/team-collaboration.png', focus: ['Engineering leadership', 'Technical hiring and standards', 'Board-ready technical communication'], questions: ['Which decisions need stronger technical ownership?', 'How should the team grow safely?', 'What should leaders understand about the product?'], receive: ['Technical leadership plan', 'Engineering standards and hiring priorities', 'Board-ready technical communication'], team: ['Regular sessions with founders and engineering leads', 'Review of product direction and delivery health', 'Hands-on support for critical decisions'], next: ['Set quarterly priorities', 'Align business and engineering', 'Support key decisions', 'Review and adapt the plan'], success: ['Founders have a reliable technical partner for major decisions', 'The engineering team has clearer standards and direction', 'Technical progress is easier to explain to boards and investors'] },
};

const guidance: Record<string, [string, string, string, string]> = {
  'tech-strategy': ['We connect technical choices to the commercial plan, so leadership can make decisions with a clear view of cost, risk, and timing.', 'Your final pack gives product, engineering, and leadership one shared direction instead of separate assumptions.', 'We work with the people who own the roadmap and the people who must deliver it, so the recommendations are grounded in reality.', 'The result is a sequence of decisions your team can take into planning, hiring, vendor discussions, and implementation.'],
  'ai-consulting': ['We look beyond the demo and focus on the workflow, data quality, review process, and financial return that make an AI feature worth operating.', 'You receive a practical plan that explains what to build, what to measure, who should review outputs, and where the risks sit.', 'We involve the business owner, technical team, and operational users early. This prevents a promising prototype from becoming an unreliable feature.', 'The next step is a focused validation plan with clear quality thresholds before any customer-facing rollout.'],
  'product-consulting': ['We turn broad ideas into decisions a delivery team can act on, including what is essential for launch and what should wait.', 'The deliverables give everyone the same view of users, priorities, scope boundaries, and the measures that define a successful launch.', 'We bring founders, product owners, and delivery leads into the same working sessions so trade-offs are made openly and early.', 'You leave ready to brief design and engineering teams with a scope that is ambitious enough to matter and focused enough to ship.'],
  'digital-transformation': ['We start with the real work people do every day, not a generic technology wish list. This shows where change will create value without disrupting operations.', 'Your plan identifies the systems, data, and workflow improvements that deserve investment first, with a realistic path for the rest.', 'We listen to the people who run the process as well as the people who manage it. That keeps the plan practical and easier to adopt.', 'The first phase is intentionally small, measurable, and safe. Once it works, the business has evidence for the next investment.'],
  'architecture-review': ['We examine how the system behaves in practice, including the decisions that make delivery slower, reliability weaker, or costs harder to control.', 'The assessment gives engineering leadership a shared record of the risks, their impact, and the order in which to address them.', 'We work directly with the people closest to the code and infrastructure, then translate the findings into clear business and delivery decisions.', 'The roadmap can be used immediately for sprint planning, technical investment discussions, and ongoing risk management.'],
  'outsourcing-advisory': ['We separate confident sales language from practical delivery evidence, so partner decisions are based on capability, risk, and continuity.', 'You receive an independent view that can be shared with leadership before signing a contract or starting a replacement process.', 'We involve the people accountable for budget, product, security, and engineering to make sure the decision works across the business.', 'The next step is a governed engagement with clear milestones, ownership, reporting expectations, and a safe handover plan.'],
  'security-compliance': ['We focus on the exposure that matters to your customers, team, and commercial commitments. The aim is to reduce risk with an achievable plan.', 'Your findings are prioritised by impact, with clear actions that engineering, operations, and leadership can understand and own.', 'We work carefully with the people responsible for systems and data. The review is practical, confidential, and designed to support improvement.', 'The resulting roadmap helps you address urgent issues, demonstrate progress, and prepare for customer reviews or compliance milestones.'],
  'fractional-cto': ['We focus on the decisions that need senior technical judgment, from product direction and architecture to hiring and communication with stakeholders.', 'You receive a leadership framework that makes responsibilities, standards, and priorities clearer for founders and the engineering team.', 'We work alongside leadership and delivery teams, bringing an independent technical perspective without adding unnecessary ceremony.', 'The next step is a regular operating rhythm that keeps product, engineering, and business decisions aligned as the company grows.'],
};

export function generateStaticParams() { return Object.keys(pages).map((service) => ({ service })); }

export default async function ConsultancyServicePage({ params }: { params: Promise<{ service: string }> }) {
  const { service } = await params; const page = pages[service]; if (!page) notFound();
  const [questionLead, receiveLead, teamLead, nextLead] = guidance[service];
  return <div className="consultancy-detail">
    <section className="section-dark relative flex min-h-[100svh] items-center overflow-hidden pt-[var(--header-h)]"><div aria-hidden className="absolute inset-0 bg-grid-dark opacity-40" /><div className="container-site relative py-16 text-center"><h1 className="mx-auto max-w-4xl text-h1 font-bold leading-[1.02] text-white">{page.title}</h1><p className="mx-auto mt-6 max-w-2xl text-body-lg leading-relaxed text-on-dark-muted">{page.intro}</p><Button href="/contact" size="lg" arrow className="mt-9 bg-amber text-white hover:bg-amber-bright">Discuss your challenge</Button></div></section>
    <section className="section-y bg-white"><div className="container-site grid items-center gap-12 lg:grid-cols-[1fr_1.05fr]"><div><h2 className="text-h2 font-bold text-ink">A focused engagement and a clear next step.</h2><div className="mt-8 space-y-4">{page.focus.map((x, i) => <div key={x} className="flex items-center gap-4 rounded-lg border border-navy/80 bg-navy px-5 py-4 shadow-card"><span className="font-bold text-amber">0{i + 1}</span><span className="font-medium text-white">{x}</span></div>)}</div></div><BrandedVisual src={page.image} alt={page.title} treatment="both" className="overflow-hidden rounded-2xl border border-line shadow-card" imageClassName="aspect-[4/3]" /></div></section>
    <section className="section-y section-light"><div className="container-site"><div className="mx-auto max-w-3xl text-center" {...revealProps()}><h2 className="text-h2 font-bold text-ink">The Questions We Answer</h2><p className="mt-5 text-body leading-relaxed text-body">{questionLead}</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{page.questions.map((x, i) => <article key={x} {...revealProps(i)} className="rounded-2xl border border-line bg-white p-7 shadow-card transition-all duration-base hover:-translate-y-1 hover:border-amber hover:shadow-card-hover"><span className="text-micro font-bold text-amber">0{i + 1}</span><h3 className="mt-8 text-[1.2rem] font-semibold text-navy">{x}</h3><p className="mt-4 text-body-sm leading-relaxed text-body">We turn this question into a documented decision, with context, options, and a clear recommendation for your team.</p></article>)}</div></div></section>
    <section className="section-y bg-navy text-white"><div className="container-site grid items-end gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div {...revealProps()}><h2 className="text-h2 font-bold text-amber">What You Receive</h2><p className="mt-5 max-w-lg text-body leading-relaxed text-white/70">{receiveLead}</p></div><div className="grid gap-4 sm:grid-cols-3">{page.receive.map((x, i) => <article key={x} {...revealProps(i)} className="border border-white/15 bg-white/[0.04] p-6 transition-colors hover:border-amber/70 hover:bg-white/[0.08]"><span className="text-micro font-bold text-amber">0{i + 1}</span><p className="mt-8 text-body font-semibold text-white">{x}</p><p className="mt-3 text-body-sm leading-relaxed text-white/65">Clear enough for leadership to use, and detailed enough for the people responsible for the next stage of work.</p></article>)}</div></div></section>
    <section className="section-y bg-white"><div className="container-site grid items-center gap-12 lg:grid-cols-2"><BrandedVisual src="/service-visuals/team-collaboration.png" alt="Eaquirs Tech collaborating with a client team" treatment="both" className="overflow-hidden rounded-2xl shadow-card" imageClassName="aspect-[4/3]" /><div><h2 className="text-h2 font-bold text-ink">How We Work With Your Team</h2><p className="mt-5 text-body leading-relaxed text-body">{teamLead}</p><div className="mt-8 space-y-4">{page.team.map((x, i) => <div key={x} {...revealProps(i)} className="flex gap-4 border-l-2 border-amber bg-amber-wash px-5 py-4"><span className="font-bold text-navy">0{i + 1}</span><p className="text-body-sm leading-relaxed text-body">{x}</p></div>)}</div></div></div></section>
    <section className="section-y section-light"><div className="container-site"><div className="mx-auto max-w-3xl text-center" {...revealProps()}><h2 className="text-h2 font-bold text-ink">What Happens Next</h2><p className="mt-5 text-body leading-relaxed text-body">{nextLead}</p></div><div className="mt-10 grid gap-4 md:grid-cols-4">{page.next.map((x, i) => <article key={x} {...revealProps(i)} className="border border-line bg-white p-6 shadow-card"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-navy text-body-sm font-bold text-amber">0{i + 1}</span><p className="mt-7 text-body-sm font-semibold leading-relaxed text-navy">{x}</p><p className="mt-3 text-body-sm leading-relaxed text-body">Each step creates a clear owner, a practical timeframe, and a way to measure progress.</p></article>)}</div><div className="mt-12 text-center"><Button href="/contact" size="lg" arrow className="bg-amber text-white hover:bg-amber-bright">Start a conversation</Button></div></div></section>
    <section className="section-y bg-white"><div className="container-site"><div className="mx-auto max-w-3xl text-center" {...revealProps()}><h2 className="text-h2 font-bold text-navy">What Success Looks Like</h2><p className="mt-5 text-body leading-relaxed text-body">A strong engagement gives your team clarity that continues after the final workshop.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{page.success.map((x, i) => <article key={x} {...revealProps(i)} className="rounded-2xl border border-amber/40 bg-amber-wash p-7"><span className="text-micro font-bold text-navy">0{i + 1}</span><h3 className="mt-6 text-[1.15rem] font-semibold text-navy">{x}</h3><p className="mt-4 text-body-sm leading-relaxed text-body">The recommendations are designed to be used in real planning, delivery, and leadership conversations.</p></article>)}</div></div></section>
  </div>;
}
